name: Lint
on:
  pull_request:
    branches:
      -main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2

     - name: Use Node.js
       uses: actions/setup-node@v4.2.2
       with:
        node-version: '20'

     - name: Install dependencies
       run: npm install

     - name: Run lint
       run: npm run lint
